import localFont from "next/font/local";
import "./globals.css";
import { Metadata } from "next";

const montserrat = localFont({
  src: "../../public/fonts/Montserrat-VariableFont_wght.ttf",
  variable: "--font-montserrat",
});

const lora = localFont({
  src: "../../public/fonts/Lora-VariableFont_wght.ttf",
  variable: "--font-lora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${lora.variable}`}>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
